nome = input('Insira seu nome: ')
capitalized = nome.capitalize()
print(capitalized)
upper = nome.upper()
print(upper)
lower = nome.lower()
print(lower)
replaced = nome.replace(" ", "")
print(replaced)
letters = len(replaced)
print(letters)